include:
  - board: xiao_ble//zmk
    shield: totem_left
    snippet: studio-rpc-usb-uart
  - board: xiao_ble//zmk
    shield: totem_right

#  - board: nice_nano@2.0.0//zmk
#    shield: felix_left nice_oled
#    snippet: studio-rpc-usb-uart
#    artifact-name: felix_left_nice_oled
#  - board: nice_nano@2.0.0//zmk
#    shield: felix_right nice_oled
#    artifact-name: felix_right_nice_oled
#  - board: nice_nano@2.0.0//zmk
#    shield: settings_reset
#    artifact-name: settings_reset

#  - board: nice_nano@2.0.0//zmk
#    shield: lily58_left nice_view_adapter nice_view_gem
#    artifact-name: lily58_left_nice_view_adapter_nice_view_gem
#  - board: nice_nano@2.0.0//zmk
#    shield: lily58_right nice_view_adapter nice_view_gem
#    artifact-name: lily58_right_nice_view_adapter_nice_view_gem
